name: Size

on:
  pull_request_target:
    types: [ opened, synchronize ]

jobs:
  update_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./
        id: size

      - uses: step-security/action-remove-labels@8b9e252cff41d87c133a7b5c5dbb536bc7a1d441 # v1.3.0
        with:
          github_token: ${{ secrets.github_token }}
          labels: ${{ steps.size.outputs.stale_labels }}

      - uses: step-security/action-add-labels@2626ee9c8332a513a229acbbfdec828feaa8d563 # v1.1.0
        with:
          github_token: ${{ secrets.github_token }}
          labels: ${{ steps.size.outputs.new_label }}
